// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wldqplgpjhloitesswul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsZHFwbGdwamhsb2l0ZXNzd3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTI1MzAsImV4cCI6MjA3Mzg2ODUzMH0.h8X02GCxxuK4zfZyZhQhKixzmyiu5-H9465FtRwf9Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});